# Generated by Django 5.2.7 on 2025-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('result_md', models.TextField()),
                ('confidence_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
